apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notification-service.fullname" . }}
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "notification-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        {{- if .Values.dapr.enabled }}
        dapr.io/enabled: "true"
        dapr.io/app-id: "{{ .Values.dapr.appId }}"
        dapr.io/app-port: "{{ .Values.dapr.appPort }}"
        dapr.io/log-level: "{{ .Values.dapr.logLevel }}"
        dapr.io/enable-api-logging: "{{ .Values.dapr.enableApiLogging }}"
        {{- end }}
      labels:
        {{- include "notification-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: {{ .Values.service.protocol }}
        envFrom:
        - configMapRef:
            name: {{ include "notification-service.fullname" . }}-config
        env:
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.email.apiKeySecret.name }}
              key: {{ .Values.email.apiKeySecret.key }}
        - name: FIREBASE_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.firebase.credentialsSecret.name }}
              key: {{ .Values.firebase.credentialsSecret.key }}
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.database.urlSecret.name }}
              key: {{ .Values.database.urlSecret.key }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
